site_name: ProxmoxCLI
repo_url: https://github.com/quonic/ProxmoxCLI
theme: readthedocs
nav:
- Home: index.md
- ProxmoxCLI Basics:
  - What is ProxmoxCLI: about.md
  - Quick Start: Quick-Start-Installation-and-Example.md
- Acknowledgements: acknowledgements.md
